fix: Drop lib{ssl,crypto}.so.1.1 workarounds in test container
Since 7ce342fb88579b560abf9e66ff20bc91f9d7048e we upgraded redis to
7.2.4 which does not link to old {ssl,crypto}.so.1.1 anymore:

    ❯ podman run -it --rm --net=host docker.io/library/redis:7.2.4@sha256:cc8b0b85fe6917a401334fd285f9a8d66fae231abcf13aadfd02975bf3924a47 bash -c "ldd /usr/local/bin/redis-cli /usr/local/bin/redis-server" | grep -i -e ssl -e crypto
            libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fb63d6cf000)
            libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fb63d24d000)
            libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f333dc9f000)
            libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f333d81d000)

This fixes the following breakage in `make build`:

    [6/6] STEP 17/28: COPY --from=redis /usr/lib/linux-gnu/libssl.so.1.1 /usr/lib/linux-gnu/
    Error: building at STEP "COPY --from=redis /usr/lib/linux-gnu/libssl.so.1.1 /usr/lib/linux-gnu/": checking on sources under "/home/michele/.local/share/containers/storage/overlay/4c8aa0061967e60ef25c6dcb51bc8868c35da68f9656d4996b87ebad9756cf65/merged": copier: stat: "/usr/lib/linux-gnu/libssl.so.1.1": no such file or directory
    make: *** [Makefile:252: test-tools-image] Error 125

Signed-off-by: Michele Baldessari <michele@acksyn.org>